version: "2"

services:
  server:
    image: nagentd:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - "./data:/var/lib/nagentd"
  
  nats:
    image: nats:latest
    ports:
      - "4222:4222"