#!/usr/bin/env ruby

require 'json'

data = ARGF.read

bits = data.split(" ")

seconds_per_minute = 60
seconds_per_hour = seconds_per_minute * 60
seconds_per_day = seconds_per_hour * 24

uptime = bits[0].to_f
days = uptime / seconds_per_day
hours = (uptime % seconds_per_day) / seconds_per_hour
minutes = (uptime % seconds_per_hour) / seconds_per_minute
seconds = uptime % seconds_per_minute

out = {
  running: uptime,
  human_running: "%dd%dh%dm%ds" % [days, hours, minutes, seconds],
  idle: bits[1].to_f,
}

puts out.to_json